# Generated by Django 5.0 on 2025-07-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todolist'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
