# Generated by Django 5.0 on 2025-07-24 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todolist_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='is_admin',
        ),
    ]
