# Generated by Django 5.0 on 2025-07-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
